apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: pvc-autoscaler-deps
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        version: v1.21.2
        namespace: cert-manager
        createNamespace: true
        setValues:
          crds.enabled: "true"
      - name: kind-prometheus
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 92.0.0
        namespace: monitoring
        createNamespace: true
        setValues:
          alertmanager.enabled: "false"
          grafana.enabled: "false"
          kubeStateMetrics.enabled: "false"
          nodeExporter.enabled: "false"
          prometheusOperator.enabled: "true"
          prometheus.enabled: "true"
---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: pvc-autoscaler
build:
  artifacts:
    - image: local-skaffold/pvc-autoscaler
      ko:
        dependencies:
          paths:
            - api/autoscaling/v1alpha1
            - cmd/pvc-autoscaler
            - internal/common
            - internal/controller/offlineresize
            - internal/healthcheck
            - internal/metrics
            - internal/metrics/source
            - internal/metrics/source/prometheus
            - internal/periodic
            - internal/target/pvcfetcher
            - internal/target/selectorfetcher
            - internal/utils
            - internal/webhook/pod
            - VERSION
        main: ./cmd/pvc-autoscaler
manifests:
  kustomize:
    paths:
      - config/overlays/kind
deploy:
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
profiles:
  - name: minikube
    activation:
      - kubeContext: pvc-autoscaler-minikube
    build:
      local:
        useDockerCLI: true
    patches:
      - op: replace
        path: /manifests/kustomize/paths/0
        value: config/overlays/minikube
